name: wearther_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.2.2
  excel: ^4.0.6
  intl: ^0.19.0
  geolocator: ^13.0.1
  geolocator_windows: ^0.2.3
  geocoding: ^3.0.0
  font_awesome_flutter: ^10.1.0
  flutter_lints: ^4.0.0
  provider: ^6.1.2
  permission_handler: ^11.3.1 # 최신 버전을 확인하고 사용하세요.


flutter:
  uses-material-design: true
  assets:
    - assets/images/naver.png
    - assets/images/google.png
    - assets/images/kakao.png
    - assets/images/instagram.png
    - assets/images/day.png
    - assets/images/sunset.png
    - assets/images/night.png
    - assets/images/skyblue.jpg

